server:
  port: 3030
  #address: 192.168.0.30

spring:
  datasource:
      url: jdbc:h2:mem:test
      driverClassName: org.h2.Driver
      username: sa
      password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
      enabled: true
      path: /h2-console
  servlet.multipart:
      enabled: true
      file-size-threshold: 2KB
      maxFileSize: 5GB
      maxRequestSize: 6GB

logging.level.root: debug

# Config
#file.upload-dir: C:/Users/karlt/IdeaProjects/home/uploads/
file.upload-dir: uploads/ #deploy