server:
  port: 3030
  #address: 192.168.0.30

spring.datasource:
  url: jdbc:h2:mem:test
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console:
  enabled: true
  path: /h2-console

spring.servlet.multipart:
  enabled: true
  file-size-threshold: 2KB
  maxFileSize: 5GB
  maxRequestSize: 6GB

logging.level.root: debug

# Config
file.upload-dir: C:/Users/karlt/IdeaProjects/home/uploads/ # /uploads/